apps/prod: 'common/scripts.yaml' provided with 'sqlite3-wait.sh' helper

diff --git a/apps/prod/common/scripts.yaml b/apps/prod/common/scripts.yaml
--- a/apps/prod/common/scripts.yaml
+++ b/apps/prod/common/scripts.yaml
@@ -114,3 +114,32 @@ data:
       /bin/sh /scripts/backup-forget.sh
     done &
     wait $!
+  sqlite3-wait.sh: |
+    #!/bin/sh
+    TARGET_DIR="$${1}"
+    TOT=15
+    set -e -o pipefail
+    if [ "$${TARGET_DIR}" = "" ]
+    then
+      echo "<sqlite3-wait.sh> $(date): error: TARGET_DIR undefined"
+      exit 1
+    fi
+    for i in $(seq 1 $${TOT})
+    do
+      PENDING_FILES="$(find "$${TARGET_DIR}" -type f \( -name "*-wal" -o -name "*-shm" \) -size +0c)"
+      if [ -z "$${PENDING_FILES}" ]
+      then
+        echo "<sqlite3-wait.sh> $(date): ($${i}/$${TOT}) all SQLite files released"
+        exit 0
+      fi
+      if [ $${i} -eq $${TOT} ]
+      then
+        echo "<sqlite3-wait.sh> $(date): ($${i}/$${TOT}) giving up waiting even though database seems to be opened"
+      else
+        echo "<sqlite3-wait.sh> $(date): ($${i}/$${TOT}) waiting for active SQLite auxiliary files to close"
+      fi
+      echo "$PENDING_FILES"
+      echo "---"
+      [ $${i} -eq $${TOT} ] && exit 0
+      sleep 1
+    done
